{% set version = "1.1.0" %}
{% set llvm_version = 13 %}

package:
  name: python-wasmer-split

source:
  url: https://github.com/wasmerio/wasmer-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 220af5b2675480daea4ebc1cede45728ce1b270cdc141ebff08ef0870cc23cfd
  patches:
    - 0000-deprecated-maturin-metadata.diff

build:
  number: 3
  skip: true  # [py<38]

outputs:
  - name: python-wasmer
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    script: build_wasmer.bat  # [win]
    build:
      run_exports:
        - python-wasmer
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - lld
        - maturin
        - pip
        - pytest
        - python
        - zlib
      run:
        - lld
        - python
        - zlib
    test:
      imports:
        - wasmer

  - name: python-wasmer-compiler-cranelift
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    script: build_wasmer.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - {{ pin_subpackage("python-wasmer", max_pin="x.x.x") }}
        - maturin
        - pip
        - pytest
        - pytest-benchmark
        - python
        - zlib
      run:
        - {{ pin_subpackage("python-wasmer", max_pin="x.x.x") }}
        - python
    test:
      imports:
        - wasmer_compiler_cranelift

  - name: python-wasmer-compiler-singlepass
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - {{ pin_subpackage("python-wasmer", max_pin="x.x.x") }}
        - maturin
        - pip
        - pytest
        - python
      run:
        - {{ pin_subpackage("python-wasmer", max_pin="x.x.x") }}
        - python
    test:
      imports:
        - wasmer_compiler_singlepass  # [unix]

  - name: python-wasmer-compiler-llvm
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - {{ pin_subpackage("python-wasmer-compiler-cranelift", max_pin="x.x.x") }}
        - clang
        - llvmdev {{ llvm_version }}.*
        - maturin
        - pip
        - pytest
        - pytest-benchmark
        - python
        - zlib
      run:
        - {{ pin_subpackage("python-wasmer", max_pin="x.x.x") }}
        - clang
        - libffi
        - libllvm{{ llvm_version }}
        - libstdcxx-ng  # [linux64]
        - python
        - zlib
    test:
      imports:
        - wasmer_compiler_llvm  # [unix]


about:
  home: https://wasmer.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebAssembly runtime for Python
  doc_url: https://docs.wasmer.io
  dev_url: https://github.com/wasmerio/wasmer

extra:
  feedstock-name: python-wasmer-split
  recipe-maintainers:
    - atrawog
    - wolfv
    - bollwyvl
